name: Array Inventory Update
description: Fill out this template with changes to be made regarding arrays.
title: "Array Inventory Update:"
labels: ["inventory update"]
assignees:
  - Kourtney-Burger
body:
  - type: markdown
    attributes:
      value: |
        If information regarding additional inventory items needs to be updated, please fill out the associated issue template. This includes hydrophones not already associated with an array, recorders, GPS units, depth sensors, computers, and other miscellaneous items.
  - type: dropdown
    id: submitting
    attributes:
      label: I'm submitting a ...
      options:
        - New array
        - Update to a current array        
  - type: input
    id: array-name
    attributes:
      label: Array Name
      description: Insert array name here. This should be a letter, followed by 2 numbers then _, followed by 4 digit hydrophone model numbers (i.e.9299, for a HTI-92 and HTI-99). If submitting a new array, contact Shannon Rankin (shannon.rankin@noaa.gov) for naming guidelines
      placeholder: ex. A02_9299
    validations:
      required: true
  - type: input
    id: array-location
    attributes:
      label: Array Current Location and Contact
      placeholder: ex. PIFSC, email@example.com
    validations:
      required: true
  - type: dropdown
    id: array-condition
    attributes:
      label: Array Condition
      options:
        - Good
        - Lost at sea
        - Needs repair
        - Other
    validations:
      required: true
  - type: input
    id: whats-wrong
    attributes:
      label: What's Wrong With The Array?
      description: If 'Needs Repair' or 'Other' was chosen above under 'Condition', explain here
      placeholder: ex. needs updated hydrophone mounts
  - type: input
    id: for-new-arrays
    attributes: 
      label: For New Arrays Only
      description: List the following information regarding the hydrophones only if you are submitting a new array; hydrophone model, serial number, and distance for all applicable channels
  - type: input
    id: additional-info
    attributes: 
      label: Any Additional Information
      description: Explain any additional information/details related to the array and associated parts
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes: 
      value: |
        Contact Kourtney Burger (kourtney.burger@noaa.gov) with any questions/comments related to this form or inventory